--- #when condition -> when condition true then execute
- hosts: devlinux
  user: ansible
  become: yes
  gather_facts: yes
  connection: ssh

  vars:
    value: 10

  tasks:
    - name: install tree
      command: yum install tree -y
      when: value == 10
