--- #multiple task yaml playbook
- hosts: devlinux
  user: ansible
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
    - name: install httpd
      action: yum pkg=httpd state=present

    - name: start httpd
      action: service name=httpd state=started

    - name: deploy index
      action: copy src=index.html dest=/var/www/html/
