--- #its a handler practical, need a trigger for running play
- hosts: devlinux
  user: ansible
  become: yes
  gather_facts: yes
  connection: ssh
  
  vars:
    pkgname: httpd
    index_path: /var/www/html

  tasks:
  - name: install apache
    action: yum pkg="{{pkgname}}" state="present"
    notify: 
      - start apache
      - deploy index

  handlers:
  - name: start apache
    action: service name="{{pkgname}}" state="started"

  - name: deploy index
    action: copy src=index.html dest="{{index_path}}"
    
